version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies
      timeout: 300
      runas: root
    - location: /scripts/start_server
      timeout: 300
      runas: root
files:
  - source: /application/index.html
    destination: /var/www/html
  - source: /application/style.css
    destination: /var/www/html
     
